data_source ecommerce:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'gifted-object-444508-n6'
    dataset: ecommerce
soda_cloud:
  host: cloud.soda.io
  api_key_id: aeae3747-9c00-4972-9e68-a7b8b5598de7
  api_key_secret: bE6R9D7Ns-DXoTpQPjzyUMnIlKtshEwC8e1EqiBXFQfz-PZmuFneMA